const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const Category = require('../models/Category');
const Product = require('../models/Product');
const Testimonial = require('../models/Testimonial');

const categories = [
  { name: 'Oversized Tees', slug: 'oversized-tees', gender: 'men', displayOrder: 1, imageUrl: '/images/categories/oversized-tees.jpg' },
  { name: 'Cargo Pants', slug: 'cargo-pants', gender: 'men', displayOrder: 2, imageUrl: '/images/categories/cargo-pants.jpg' },
  { name: 'Hoodies', slug: 'hoodies', gender: 'men', displayOrder: 3, imageUrl: '/images/categories/hoodies.jpg' },
  { name: 'Accessories', slug: 'accessories', gender: 'all', displayOrder: 4, imageUrl: '/images/categories/accessories.jpg' },
  { name: "Women's Tops", slug: 'womens-tops', gender: 'women', displayOrder: 5, imageUrl: '/images/categories/womens-tops.jpg' },
  { name: 'Joggers', slug: 'joggers', gender: 'all', displayOrder: 6, imageUrl: '/images/categories/joggers.jpg' },
  { name: 'Caps & Hats', slug: 'caps-hats', gender: 'all', displayOrder: 7, imageUrl: '/images/categories/caps-hats.jpg' },
  { name: 'Denim', slug: 'denim', gender: 'all', displayOrder: 8, imageUrl: '/images/categories/denim.jpg' },
];

const testimonials = [
  {
    customerName: 'Farhan R.',
    location: 'Dhaka',
    rating: 5,
    quote: "Finally a local brand that actually slaps. The cargo pants fit is insane. 🔥",
  },
  {
    customerName: 'Tasnim A.',
    location: 'Chittagong',
    rating: 5,
    quote: "Ordered the mesh tank top — the quality is on another level. Deshi Drip never misses.",
  },
  {
    customerName: 'Rifat H.',
    location: 'Sylhet',
    rating: 4,
    quote: "Bhai the acid wash hoodie hits different. Got compliments everywhere I went.",
  },
  {
    customerName: 'Nusrat J.',
    location: 'Dhaka',
    rating: 5,
    quote: "Loved the packaging, loved the vibe, loved the fit. This is the BD brand we deserved.",
  },
  {
    customerName: 'Shakib M.',
    location: 'Rajshahi',
    rating: 5,
    quote: "Fast delivery and the quality is genuinely premium. Will cop again for sure. 💯",
  },
];

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB connected for seeding...');

    // Clear existing
    await Category.deleteMany();
    await Product.deleteMany();
    await Testimonial.deleteMany();
    console.log('🗑️  Cleared existing data');

    // Seed categories
    const createdCats = await Category.insertMany(categories);
    console.log(`✅ ${createdCats.length} categories seeded`);

    const getCat = (slug) => createdCats.find((c) => c.slug === slug)._id;

    const products = [
      {
        name: 'Camo Cargo Pants',
        slug: 'camo-cargo-pants',
        imageUrl: '/images/products/camo_cargo_pants.jpg',
        price: 1899,
        originalPrice: 2299,
        category: getCat('cargo-pants'),
        gender: 'men',
        description: 'Multi-pocket camo cargo trousers with a relaxed baggy fit. Street-ready every day.',
        tags: ['cargo', 'camo', 'streetwear', 'baggy'],
        badge: 'New Drop',
        isFeatured: true,
        isAvailable: true,
      },
      {
        name: 'Acid Wash Hoodie',
        slug: 'acid-wash-hoodie',
        imageUrl: '/images/products/Acid Wash Hoodie.jpg',
        price: 1599,
        originalPrice: 1999,
        category: getCat('hoodies'),
        gender: 'men',
        description: 'Heavyweight 380gsm acid-washed fleece hoodie. Faded, raw, and straight from Dhaka.',
        tags: ['hoodie', 'acid wash', 'oversized', 'fleece'],
        badge: 'Hot',
        isFeatured: true,
        isAvailable: true,
      },
      {
        name: 'Logo Oversized Tee',
        slug: 'logo-oversized-tee',
        imageUrl: '/images/products/Logo Oversized Tee.png',
        price: 899,
        originalPrice: 1099,
        category: getCat('oversized-tees'),
        gender: 'men',
        description: 'Clean oversized tee with the Deshi Drip chest logo. 100% ring-spun cotton.',
        tags: ['tee', 'oversized', 'logo', 'cotton'],
        badge: 'New Drop',
        isFeatured: true,
        isAvailable: true,
      },
      {
        name: 'Mesh Tank Top',
        slug: 'mesh-tank-top',
        imageUrl: '/images/products/Mesh Tank Top.jpg',
        price: 799,
        originalPrice: 999,
        category: getCat('womens-tops'),
        gender: 'women',
        description: 'Breathable mesh tank for the streets. Cropped, bold, and made to be seen.',
        tags: ['tank', 'mesh', 'crop', 'summer'],
        badge: 'New Drop',
        isFeatured: true,
        isAvailable: true,
      },
      {
        name: 'Bucket Hat',
        slug: 'bucket-hat',
        imageUrl: '/images/products/Bucket Hat.webp',
        price: 699,
        originalPrice: 899,
        category: getCat('caps-hats'),
        gender: 'unisex',
        description: 'Reversible bucket hat with Deshi Drip embroidery. Two looks, one hat.',
        tags: ['hat', 'bucket', 'reversible', 'unisex'],
        badge: '',
        isFeatured: true,
        isAvailable: true,
      },
      {
        name: 'Wide-leg Joggers',
        slug: 'wide-leg-joggers',
        imageUrl: '/images/products/Wide-leg Joggers.webp',
        price: 1299,
        originalPrice: 1599,
        category: getCat('joggers'),
        gender: 'unisex',
        description: 'Ultra-wide leg joggers with an elastic waistband. Comfortable enough for anywhere.',
        tags: ['joggers', 'wide leg', 'relaxed', 'casual'],
        badge: 'Hot',
        isFeatured: true,
        isAvailable: true,
      },
      {
        name: 'Raw Denim Jacket',
        slug: 'raw-denim-jacket',
        imageUrl: '/images/products/Raw Denim Jacket.jpg',
        price: 2499,
        originalPrice: 2999,
        category: getCat('denim'),
        gender: 'men',
        description: 'Selvedge-inspired raw denim jacket with worn-in detailing. Statement outerwear.',
        tags: ['denim', 'jacket', 'raw', 'premium'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: "Women's Cargo Jogger",
        slug: 'womens-cargo-jogger',
        imageUrl: "/images/products/Women's Cargo Jogger.webp",
        price: 1499,
        originalPrice: 1799,
        category: getCat('joggers'),
        gender: 'women',
        description: 'Tapered cargo jogger for women. Side pockets, ankle drawstring, maximum drip.',
        tags: ['jogger', 'cargo', 'women', 'tapered'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: 'Snapback Cap',
        slug: 'snapback-cap',
        imageUrl: '/images/products/Snapback Cap.jpg',
        price: 599,
        originalPrice: 799,
        category: getCat('caps-hats'),
        gender: 'unisex',
        description: 'Flat brim snapback with green Deshi Drip logo patch. Adjustable fit.',
        tags: ['cap', 'snapback', 'unisex', 'logo'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: 'Striped Oversized Shirt',
        slug: 'striped-oversized-shirt',
        imageUrl: '/images/products/Striped Oversized Shirt.jpg',
        price: 1099,
        originalPrice: 1399,
        category: getCat('oversized-tees'),
        gender: 'men',
        description: 'Boxy oversized striped shirt. Wear open as a layer or buttoned for a clean look.',
        tags: ['shirt', 'striped', 'oversized', 'layering'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: "Women's Graphic Tee",
        slug: 'womens-graphic-tee',
        imageUrl: "/images/products/Women's Graphic Tee.jpg",
        price: 849,
        originalPrice: 1049,
        category: getCat('womens-tops'),
        gender: 'women',
        description: 'Bold graphic print tee for women. Slightly cropped, ultra soft 200gsm cotton.',
        tags: ['tee', 'graphic', 'women', 'cropped'],
        badge: 'Hot',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: 'Crossbody Utility Bag',
        slug: 'crossbody-utility-bag',
        imageUrl: '/images/products/Crossbody Utility Bag.jpg',
        price: 1199,
        originalPrice: 1499,
        category: getCat('accessories'),
        gender: 'unisex',
        description: 'Waterproof nylon crossbody with multiple compartments. Built for the streets.',
        tags: ['bag', 'crossbody', 'utility', 'accessories'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },

      // ── Extra Men's styles ──────────────────────────────────────────
      {
        name: 'Washed Black Hoodie',
        slug: 'washed-black-hoodie',
        imageUrl: '/images/products/Washed Black Hoodie.jpg',
        price: 1699,
        originalPrice: 1999,
        category: getCat('hoodies'),
        gender: 'men',
        description: 'Garment-washed black hoodie with a lived-in feel. 400gsm French terry, relaxed fit.',
        tags: ['hoodie', 'washed', 'black', 'premium'],
        badge: 'New Drop',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: 'Tactical Cargo Shorts',
        slug: 'tactical-cargo-shorts',
        imageUrl: '/images/products/Tactical Cargo Shorts.jpg',
        price: 1099,
        originalPrice: 1399,
        category: getCat('cargo-pants'),
        gender: 'men',
        description: 'Knee-length cargo shorts with 6 utility pockets and adjustable waistband. Summer-ready.',
        tags: ['cargo', 'shorts', 'summer', 'utility'],
        badge: 'Hot',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: 'Graphic Print Hoodie',
        slug: 'graphic-print-hoodie',
        imageUrl: '/images/products/Graphic Print Hoodie.jpg',
        price: 1799,
        originalPrice: 2199,
        category: getCat('hoodies'),
        gender: 'men',
        description: 'All-over graphic printed hoodie with bold Dhaka-inspired artwork. Limited run.',
        tags: ['hoodie', 'graphic', 'art', 'limited'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: 'Slim Fit Denim Jeans',
        slug: 'slim-fit-denim-jeans',
        imageUrl: '/images/products/Slim Fit Denim Jeans.webp',
        price: 1999,
        originalPrice: 2499,
        category: getCat('denim'),
        gender: 'men',
        description: 'Mid-wash slim-fit denim with subtle distressing at the knees. Everyday staple.',
        tags: ['denim', 'jeans', 'slim', 'mid-wash'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: 'Drip Embroidered Cap',
        slug: 'drip-embroidered-cap',
        imageUrl: '/images/products/Drip Embroidered Cap.jpg',
        price: 649,
        originalPrice: 849,
        category: getCat('caps-hats'),
        gender: 'men',
        description: '6-panel structured cap with embroidered DRIP lettering on the front. Adjustable strap.',
        tags: ['cap', 'embroidered', '6-panel', 'logo'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },

      // ── Extra Women's styles ────────────────────────────────────────
      {
        name: "Women's Oversized Hoodie",
        slug: 'womens-oversized-hoodie',
        imageUrl: "/images/products/Women's Oversized Hoodie.webp",
        price: 1549,
        originalPrice: 1899,
        category: getCat('hoodies'),
        gender: 'women',
        description: 'Drop-shoulder oversized hoodie in a soft lavender-grey. Cozy meets street-ready.',
        tags: ['hoodie', 'oversized', 'women', 'cozy'],
        badge: 'New Drop',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: 'Corset-Style Tank',
        slug: 'corset-style-tank',
        imageUrl: '/images/products/Corset-Style Tank.webp',
        price: 899,
        originalPrice: 1099,
        category: getCat('womens-tops'),
        gender: 'women',
        description: 'Structured corset-style tank with lace-up detailing. Bold silhouette, soft fabric.',
        tags: ['tank', 'corset', 'structured', 'bold'],
        badge: 'Hot',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: "Women's Wide-Leg Denim",
        slug: 'womens-wide-leg-denim',
        imageUrl: "/images/products/Women's Wide-Leg Denim.webp",
        price: 2199,
        originalPrice: 2699,
        category: getCat('denim'),
        gender: 'women',
        description: 'High-rise wide-leg denim with raw hem. Effortlessly cool, infinitely wearable.',
        tags: ['denim', 'wide-leg', 'high-rise', 'raw hem'],
        badge: 'New Drop',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: 'Printed Wrap Skirt',
        slug: 'printed-wrap-skirt',
        imageUrl: '/images/products/Printed Wrap Skirt.jpg',
        price: 1099,
        originalPrice: 1299,
        category: getCat('womens-tops'),
        gender: 'women',
        description: 'Midi wrap skirt with abstract street-art print. Adjustable tie waist for a perfect fit.',
        tags: ['skirt', 'wrap', 'print', 'midi'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: 'Cropped Windbreaker',
        slug: 'cropped-windbreaker',
        imageUrl: '/images/products/Cropped Windbreaker.webp',
        price: 1899,
        originalPrice: 2299,
        category: getCat('womens-tops'),
        gender: 'women',
        description: 'Lightweight cropped windbreaker jacket with a zip front and side pockets. Layer it up.',
        tags: ['jacket', 'windbreaker', 'cropped', 'layer'],
        badge: 'Hot',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: "Women's Jogger Set",
        slug: 'womens-jogger-set',
        imageUrl: "/images/products/Women's Jogger Set.webp",
        price: 2199,
        originalPrice: 2699,
        category: getCat('joggers'),
        gender: 'women',
        description: 'Matching crop top + jogger co-ord set in brushed fleece. Comfort that hits different.',
        tags: ['set', 'jogger', 'co-ord', 'fleece'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },
      {
        name: "Women's Bucket Hat",
        slug: 'womens-bucket-hat',
        imageUrl: "/images/products/Women's Bucket Hat.webp",
        price: 699,
        originalPrice: 899,
        category: getCat('caps-hats'),
        gender: 'women',
        description: 'Floral-embroidered bucket hat in washed cotton. Adjustable inner band.',
        tags: ['hat', 'bucket', 'embroidered', 'floral'],
        badge: '',
        isFeatured: false,
        isAvailable: true,
      },
    ];

    const createdProducts = await Product.insertMany(products);
    console.log(`✅ ${createdProducts.length} products seeded`);

    const createdTestimonials = await Testimonial.insertMany(testimonials);
    console.log(`✅ ${createdTestimonials.length} testimonials seeded`);

    console.log('🎉 Database seeded successfully!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err);
    process.exit(1);
  }
};

seedData();
